events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location /api/ {
            proxy_pass https://huawei-cloud-final-app.onrender.com;
            proxy_set_header Host huawei-cloud-final-app.onrender.com;
            proxy_ssl_server_name on;
        }

        location ~ ^/[a-zA-Z0-9]+$ {
            proxy_pass https://huawei-cloud-final-app.onrender.com;
            proxy_set_header Host huawei-cloud-final-app.onrender.com;
            proxy_ssl_server_name on;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}