events {}

http {
    include /etc/nginx/mime.types;

    upstream backend {
        server backend:8000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }

        location ~ ^/[a-zA-Z0-9]+$ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}